package level
def @level load_1701418(){
	author("TheblueMan003")
	block.set(~ ~5 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~5, minecraft:red_terracotta)
	block.set(~ ~7 ~5, minecraft:green_terracotta)
	block.set(~ ~8 ~5, minecraft:brown_terracotta)
	block.set(~ ~9 ~5, minecraft:yellow_terracotta)
	block.set(~ ~5 ~6, minecraft:white_terracotta)
	block.set(~ ~6 ~6, minecraft:green_terracotta)
	block.set(~ ~7 ~6, minecraft:white_terracotta)
	block.set(~ ~8 ~6, minecraft:green_terracotta)
	block.set(~ ~9 ~6, minecraft:white_terracotta)
	block.set(~ ~5 ~7, minecraft:white_terracotta)
	block.set(~ ~6 ~7, minecraft:pink_terracotta)
	block.set(~ ~7 ~7, minecraft:purple_terracotta)
	block.set(~ ~8 ~7, minecraft:light_gray_terracotta)
	block.set(~ ~9 ~7, minecraft:white_terracotta)
	block.set(~ ~5 ~8, minecraft:white_terracotta)
	block.set(~ ~6 ~8, minecraft:blue_terracotta)
	block.set(~ ~7 ~8, minecraft:white_terracotta)
	block.set(~ ~8 ~8, minecraft:blue_terracotta)
	block.set(~ ~9 ~8, minecraft:white_terracotta)
	block.set(~ ~5 ~9, minecraft:magenta_terracotta)
	block.set(~ ~6 ~9, minecraft:red_terracotta)
	block.set(~ ~7 ~9, minecraft:blue_terracotta)
	block.set(~ ~8 ~9, minecraft:brown_terracotta)
	block.set(~ ~9 ~9, minecraft:lime_terracotta)
}