package level
def @level load_2425760(){
	author("TheblueMan003")
	block.set(~ ~5 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~4, minecraft:yellow_terracotta)
	block.set(~ ~11 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~12 ~4, minecraft:yellow_terracotta)
	block.set(~ ~5 ~5, minecraft:white_terracotta)
	block.set(~ ~6 ~5, minecraft:magenta_terracotta)
	block.set(~ ~7 ~5, minecraft:yellow_terracotta)
	block.set(~ ~11 ~5, minecraft:white_terracotta)
	block.set(~ ~12 ~5, minecraft:white_terracotta)
	block.set(~ ~5 ~6, minecraft:white_terracotta)
	block.set(~ ~7 ~6, minecraft:magenta_terracotta)
	block.set(~ ~8 ~6, minecraft:yellow_terracotta)
	block.set(~ ~11 ~6, minecraft:white_terracotta)
	block.set(~ ~12 ~6, minecraft:white_terracotta)
	block.set(~ ~5 ~7, minecraft:white_terracotta)
	block.set(~ ~6 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~7, minecraft:yellow_terracotta)
	block.set(~ ~8 ~7, minecraft:magenta_terracotta)
	block.set(~ ~9 ~7, minecraft:yellow_terracotta)
	block.set(~ ~11 ~7, minecraft:white_terracotta)
	block.set(~ ~12 ~7, minecraft:white_terracotta)
	block.set(~ ~5 ~8, minecraft:white_terracotta)
	block.set(~ ~6 ~8, minecraft:white_terracotta)
	block.set(~ ~7 ~8, minecraft:magenta_terracotta)
	block.set(~ ~8 ~8, minecraft:yellow_terracotta)
	block.set(~ ~9 ~8, minecraft:magenta_terracotta)
	block.set(~ ~10 ~8, minecraft:yellow_terracotta)
	block.set(~ ~11 ~8, minecraft:white_terracotta)
	block.set(~ ~12 ~8, minecraft:white_terracotta)
	block.set(~ ~5 ~9, minecraft:white_terracotta)
	block.set(~ ~6 ~9, minecraft:white_terracotta)
	block.set(~ ~8 ~9, minecraft:magenta_terracotta)
	block.set(~ ~9 ~9, minecraft:yellow_terracotta)
	block.set(~ ~10 ~9, minecraft:magenta_terracotta)
	block.set(~ ~11 ~9, minecraft:lime_terracotta)
	block.set(~ ~12 ~9, minecraft:white_terracotta)
	block.set(~ ~5 ~10, minecraft:magenta_terracotta)
	block.set(~ ~6 ~10, minecraft:lime_terracotta)
	block.set(~ ~9 ~10, minecraft:magenta_terracotta)
	block.set(~ ~10 ~10, minecraft:orange_terracotta)
	block.set(~ ~11 ~10, minecraft:orange_terracotta)
	block.set(~ ~12 ~10, minecraft:lime_terracotta)
}