package level
def @level load_3888345(){
	author("TheblueMan003")
	block.set(~ ~4 ~3, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~3, minecraft:orange_terracotta)
	block.set(~ ~6 ~3, minecraft:gray_terracotta)
	block.set(~ ~7 ~3, minecraft:orange_terracotta)
	block.set(~ ~8 ~3, minecraft:orange_terracotta)
	block.set(~ ~9 ~3, minecraft:yellow_terracotta)
	block.set(~ ~4 ~4, minecraft:white_terracotta)
	block.set(~ ~6 ~4, minecraft:white_terracotta)
	block.set(~ ~9 ~4, minecraft:white_terracotta)
	block.set(~ ~4 ~5, minecraft:pink_terracotta)
	block.set(~ ~5 ~5, minecraft:orange_terracotta)
	block.set(~ ~6 ~5, minecraft:light_gray_terracotta)
	block.set(~ ~9 ~5, minecraft:white_terracotta)
	block.set(~ ~4 ~6, minecraft:white_terracotta)
	block.set(~ ~6 ~6, minecraft:white_terracotta)
	block.set(~ ~9 ~6, minecraft:white_terracotta)
	block.set(~ ~4 ~7, minecraft:white_terracotta)
	block.set(~ ~6 ~7, minecraft:pink_terracotta)
	block.set(~ ~7 ~7, minecraft:orange_terracotta)
	block.set(~ ~8 ~7, minecraft:orange_terracotta)
	block.set(~ ~9 ~7, minecraft:light_gray_terracotta)
	block.set(~ ~4 ~8, minecraft:white_terracotta)
	block.set(~ ~6 ~8, minecraft:white_terracotta)
	block.set(~ ~9 ~8, minecraft:white_terracotta)
	block.set(~ ~4 ~9, minecraft:magenta_terracotta)
	block.set(~ ~5 ~9, minecraft:orange_terracotta)
	block.set(~ ~6 ~9, minecraft:cyan_terracotta)
	block.set(~ ~7 ~9, minecraft:orange_terracotta)
	block.set(~ ~8 ~9, minecraft:orange_terracotta)
	block.set(~ ~9 ~9, minecraft:lime_terracotta)
}