package level
def @level load_457167(){
	author("TheblueMan003")
	block.set(~ ~3 ~3, minecraft:brown_terracotta)
	block.set(~ ~4 ~3, minecraft:orange_terracotta)
	block.set(~ ~5 ~3, minecraft:yellow_terracotta)
	block.set(~ ~5 ~4, minecraft:white_terracotta)
	block.set(~ ~1 ~5, minecraft:green_terracotta)
	block.set(~ ~4 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~5, minecraft:cyan_terracotta)
	block.set(~ ~6 ~5, minecraft:yellow_terracotta)
	block.set(~ ~8 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~5, minecraft:yellow_terracotta)
	block.set(~ ~11 ~5, minecraft:green_terracotta)
	block.set(~ ~1 ~6, minecraft:magenta_terracotta)
	block.set(~ ~2 ~6, minecraft:orange_terracotta)
	block.set(~ ~3 ~6, minecraft:orange_terracotta)
	block.set(~ ~4 ~6, minecraft:light_gray_terracotta)
	block.set(~ ~6 ~6, minecraft:pink_terracotta)
	block.set(~ ~7 ~6, minecraft:orange_terracotta)
	block.set(~ ~8 ~6, minecraft:light_gray_terracotta)
	block.set(~ ~9 ~6, minecraft:pink_terracotta)
	block.set(~ ~10 ~6, minecraft:orange_terracotta)
	block.set(~ ~11 ~6, minecraft:lime_terracotta)
	block.set(~ ~1 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~2 ~7, minecraft:orange_terracotta)
	block.set(~ ~3 ~7, minecraft:orange_terracotta)
	block.set(~ ~4 ~7, minecraft:light_gray_terracotta)
	block.set(~ ~6 ~7, minecraft:pink_terracotta)
	block.set(~ ~7 ~7, minecraft:orange_terracotta)
	block.set(~ ~8 ~7, minecraft:light_gray_terracotta)
	block.set(~ ~9 ~7, minecraft:pink_terracotta)
	block.set(~ ~10 ~7, minecraft:orange_terracotta)
	block.set(~ ~11 ~7, minecraft:orange_terracotta)
	block.set(~ ~12 ~7, minecraft:yellow_terracotta)
	block.set(~ ~1 ~8, minecraft:blue_terracotta)
	block.set(~ ~4 ~8, minecraft:magenta_terracotta)
	block.set(~ ~5 ~8, minecraft:gray_terracotta)
	block.set(~ ~6 ~8, minecraft:lime_terracotta)
	block.set(~ ~8 ~8, minecraft:magenta_terracotta)
	block.set(~ ~9 ~8, minecraft:lime_terracotta)
	block.set(~ ~12 ~8, minecraft:blue_terracotta)
	block.set(~ ~5 ~9, minecraft:white_terracotta)
	block.set(~ ~3 ~10, minecraft:brown_terracotta)
	block.set(~ ~4 ~10, minecraft:orange_terracotta)
	block.set(~ ~5 ~10, minecraft:lime_terracotta)
}