package level
def @level load_4637366(){
	author("TheblueMan003")
	block.set(~ ~9 ~4, minecraft:green_terracotta)
	block.set(~ ~7 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~5, minecraft:orange_terracotta)
	block.set(~ ~9 ~5, minecraft:cyan_terracotta)
	block.set(~ ~10 ~5, minecraft:yellow_terracotta)
	block.set(~ ~6 ~6, minecraft:brown_terracotta)
	block.set(~ ~7 ~6, minecraft:light_gray_terracotta)
	block.set(~ ~8 ~6, minecraft:brown_terracotta)
	block.set(~ ~9 ~6, minecraft:red_terracotta)
	block.set(~ ~10 ~6, minecraft:white_terracotta)
	block.set(~ ~7 ~7, minecraft:white_terracotta)
	block.set(~ ~8 ~7, minecraft:brown_terracotta)
	block.set(~ ~9 ~7, minecraft:red_terracotta)
	block.set(~ ~10 ~7, minecraft:pink_terracotta)
	block.set(~ ~11 ~7, minecraft:red_terracotta)
	block.set(~ ~7 ~8, minecraft:magenta_terracotta)
	block.set(~ ~8 ~8, minecraft:gray_terracotta)
	block.set(~ ~9 ~8, minecraft:orange_terracotta)
	block.set(~ ~10 ~8, minecraft:lime_terracotta)
	block.set(~ ~8 ~9, minecraft:blue_terracotta)
}