package level
def @level load_5788824(){
	author("TheblueMan003")
	block.set(~ ~6 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~4, minecraft:orange_terracotta)
	block.set(~ ~8 ~4, minecraft:red_terracotta)
	block.set(~ ~9 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~4, minecraft:gray_terracotta)
	block.set(~ ~11 ~4, minecraft:red_terracotta)
	block.set(~ ~6 ~5, minecraft:white_terracotta)
	block.set(~ ~7 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~5, minecraft:gray_terracotta)
	block.set(~ ~9 ~5, minecraft:purple_terracotta)
	block.set(~ ~10 ~5, minecraft:light_gray_terracotta)
	block.set(~ ~6 ~6, minecraft:pink_terracotta)
	block.set(~ ~7 ~6, minecraft:purple_terracotta)
	block.set(~ ~8 ~6, minecraft:lime_terracotta)
	block.set(~ ~9 ~6, minecraft:white_terracotta)
	block.set(~ ~10 ~6, minecraft:magenta_terracotta)
	block.set(~ ~11 ~6, minecraft:red_terracotta)
	block.set(~ ~6 ~7, minecraft:magenta_terracotta)
	block.set(~ ~7 ~7, minecraft:cyan_terracotta)
	block.set(~ ~8 ~7, minecraft:red_terracotta)
	block.set(~ ~9 ~7, minecraft:magenta_terracotta)
	block.set(~ ~10 ~7, minecraft:orange_terracotta)
	block.set(~ ~11 ~7, minecraft:red_terracotta)
}