package level
def @level load_5905034(){
	author("TheblueMan003")
	block.set(~ ~6 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~4, minecraft:yellow_terracotta)
	block.set(~ ~8 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~4, minecraft:yellow_terracotta)
	block.set(~ ~6 ~5, minecraft:magenta_terracotta)
	block.set(~ ~7 ~5, minecraft:lime_terracotta)
	block.set(~ ~8 ~5, minecraft:white_terracotta)
	block.set(~ ~9 ~5, minecraft:pink_terracotta)
	block.set(~ ~10 ~5, minecraft:orange_terracotta)
	block.set(~ ~11 ~5, minecraft:yellow_terracotta)
	block.set(~ ~6 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~6, minecraft:yellow_terracotta)
	block.set(~ ~8 ~6, minecraft:white_terracotta)
	block.set(~ ~9 ~6, minecraft:white_terracotta)
	block.set(~ ~10 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~11 ~6, minecraft:lime_terracotta)
	block.set(~ ~6 ~7, minecraft:white_terracotta)
	block.set(~ ~7 ~7, minecraft:white_terracotta)
	block.set(~ ~8 ~7, minecraft:white_terracotta)
	block.set(~ ~9 ~7, minecraft:white_terracotta)
	block.set(~ ~10 ~7, minecraft:white_terracotta)
	block.set(~ ~6 ~8, minecraft:magenta_terracotta)
	block.set(~ ~7 ~8, minecraft:lime_terracotta)
	block.set(~ ~8 ~8, minecraft:white_terracotta)
	block.set(~ ~9 ~8, minecraft:white_terracotta)
	block.set(~ ~10 ~8, minecraft:magenta_terracotta)
	block.set(~ ~11 ~8, minecraft:yellow_terracotta)
	block.set(~ ~6 ~9, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~9, minecraft:yellow_terracotta)
	block.set(~ ~8 ~9, minecraft:white_terracotta)
	block.set(~ ~9 ~9, minecraft:pink_terracotta)
	block.set(~ ~10 ~9, minecraft:orange_terracotta)
	block.set(~ ~11 ~9, minecraft:lime_terracotta)
	block.set(~ ~6 ~10, minecraft:magenta_terracotta)
	block.set(~ ~7 ~10, minecraft:lime_terracotta)
	block.set(~ ~8 ~10, minecraft:magenta_terracotta)
	block.set(~ ~9 ~10, minecraft:lime_terracotta)
}