package level
def @level load_6055057(){
	author("TheblueMan003")
	block.set(~ ~4 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~4, minecraft:orange_terracotta)
	block.set(~ ~6 ~4, minecraft:orange_terracotta)
	block.set(~ ~7 ~4, minecraft:orange_terracotta)
	block.set(~ ~8 ~4, minecraft:gray_terracotta)
	block.set(~ ~9 ~4, minecraft:orange_terracotta)
	block.set(~ ~10 ~4, minecraft:yellow_terracotta)
	block.set(~ ~4 ~5, minecraft:white_terracotta)
	block.set(~ ~8 ~5, minecraft:pink_terracotta)
	block.set(~ ~9 ~5, minecraft:red_terracotta)
	block.set(~ ~10 ~5, minecraft:white_terracotta)
	block.set(~ ~4 ~6, minecraft:white_terracotta)
	block.set(~ ~5 ~6, minecraft:green_terracotta)
	block.set(~ ~8 ~6, minecraft:pink_terracotta)
	block.set(~ ~9 ~6, minecraft:orange_terracotta)
	block.set(~ ~10 ~6, minecraft:lime_terracotta)
	block.set(~ ~4 ~7, minecraft:white_terracotta)
	block.set(~ ~5 ~7, minecraft:white_terracotta)
	block.set(~ ~8 ~7, minecraft:white_terracotta)
	block.set(~ ~4 ~8, minecraft:white_terracotta)
	block.set(~ ~5 ~8, minecraft:blue_terracotta)
	block.set(~ ~8 ~8, minecraft:pink_terracotta)
	block.set(~ ~9 ~8, minecraft:orange_terracotta)
	block.set(~ ~10 ~8, minecraft:yellow_terracotta)
	block.set(~ ~4 ~9, minecraft:white_terracotta)
	block.set(~ ~8 ~9, minecraft:pink_terracotta)
	block.set(~ ~9 ~9, minecraft:red_terracotta)
	block.set(~ ~10 ~9, minecraft:white_terracotta)
	block.set(~ ~4 ~10, minecraft:magenta_terracotta)
	block.set(~ ~5 ~10, minecraft:orange_terracotta)
	block.set(~ ~6 ~10, minecraft:orange_terracotta)
	block.set(~ ~7 ~10, minecraft:orange_terracotta)
	block.set(~ ~8 ~10, minecraft:cyan_terracotta)
	block.set(~ ~9 ~10, minecraft:orange_terracotta)
	block.set(~ ~10 ~10, minecraft:lime_terracotta)
}