package level
def @level load_6763011(){
	author("TheblueMan003")
	block.set(~ ~4 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~6, minecraft:orange_terracotta)
	block.set(~ ~6 ~6, minecraft:orange_terracotta)
	block.set(~ ~7 ~6, minecraft:orange_terracotta)
	block.set(~ ~8 ~6, minecraft:orange_terracotta)
	block.set(~ ~9 ~6, minecraft:orange_terracotta)
	block.set(~ ~10 ~6, minecraft:red_terracotta)
	block.set(~ ~4 ~7, minecraft:white_terracotta)
	block.set(~ ~5 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~7, minecraft:gray_terracotta)
	block.set(~ ~7 ~7, minecraft:orange_terracotta)
	block.set(~ ~8 ~7, minecraft:orange_terracotta)
	block.set(~ ~9 ~7, minecraft:gray_terracotta)
	block.set(~ ~10 ~7, minecraft:red_terracotta)
	block.set(~ ~4 ~8, minecraft:blue_terracotta)
	block.set(~ ~5 ~8, minecraft:blue_terracotta)
	block.set(~ ~6 ~8, minecraft:blue_terracotta)
	block.set(~ ~9 ~8, minecraft:magenta_terracotta)
	block.set(~ ~10 ~8, minecraft:red_terracotta)
}