package level
def @level load_6927351(){
	author("TheblueMan003")
	block.set(~ ~4 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~6, minecraft:red_terracotta)
	block.set(~ ~6 ~6, minecraft:brown_terracotta)
	block.set(~ ~7 ~6, minecraft:yellow_terracotta)
	block.set(~ ~8 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~6, minecraft:red_terracotta)
	block.set(~ ~3 ~7, minecraft:brown_terracotta)
	block.set(~ ~4 ~7, minecraft:light_gray_terracotta)
	block.set(~ ~5 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~7, minecraft:gray_terracotta)
	block.set(~ ~7 ~7, minecraft:cyan_terracotta)
	block.set(~ ~8 ~7, minecraft:purple_terracotta)
	block.set(~ ~9 ~7, minecraft:red_terracotta)
	block.set(~ ~3 ~8, minecraft:light_blue_terracotta)
	block.set(~ ~4 ~8, minecraft:light_gray_terracotta)
	block.set(~ ~5 ~8, minecraft:pink_terracotta)
	block.set(~ ~6 ~8, minecraft:lime_terracotta)
	block.set(~ ~8 ~8, minecraft:magenta_terracotta)
	block.set(~ ~9 ~8, minecraft:yellow_terracotta)
	block.set(~ ~3 ~9, minecraft:blue_terracotta)
	block.set(~ ~4 ~9, minecraft:blue_terracotta)
	block.set(~ ~5 ~9, minecraft:magenta_terracotta)
	block.set(~ ~6 ~9, minecraft:red_terracotta)
	block.set(~ ~7 ~9, minecraft:brown_terracotta)
	block.set(~ ~8 ~9, minecraft:orange_terracotta)
	block.set(~ ~9 ~9, minecraft:lime_terracotta)
}