package level
def @level load_7057357(){
	author("TheblueMan003")
	block.set(~ ~5 ~3, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~3, minecraft:orange_terracotta)
	block.set(~ ~7 ~3, minecraft:yellow_terracotta)
	block.set(~ ~5 ~4, minecraft:white_terracotta)
	block.set(~ ~7 ~4, minecraft:pink_terracotta)
	block.set(~ ~8 ~4, minecraft:orange_terracotta)
	block.set(~ ~9 ~4, minecraft:yellow_terracotta)
	block.set(~ ~5 ~5, minecraft:white_terracotta)
	block.set(~ ~7 ~5, minecraft:white_terracotta)
	block.set(~ ~9 ~5, minecraft:white_terracotta)
	block.set(~ ~11 ~5, minecraft:green_terracotta)
	block.set(~ ~4 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~6, minecraft:cyan_terracotta)
	block.set(~ ~6 ~6, minecraft:orange_terracotta)
	block.set(~ ~7 ~6, minecraft:cyan_terracotta)
	block.set(~ ~8 ~6, minecraft:orange_terracotta)
	block.set(~ ~9 ~6, minecraft:cyan_terracotta)
	block.set(~ ~10 ~6, minecraft:gray_terracotta)
	block.set(~ ~11 ~6, minecraft:lime_terracotta)
	block.set(~ ~4 ~7, minecraft:magenta_terracotta)
	block.set(~ ~5 ~7, minecraft:gray_terracotta)
	block.set(~ ~6 ~7, minecraft:orange_terracotta)
	block.set(~ ~7 ~7, minecraft:gray_terracotta)
	block.set(~ ~8 ~7, minecraft:orange_terracotta)
	block.set(~ ~9 ~7, minecraft:gray_terracotta)
	block.set(~ ~10 ~7, minecraft:cyan_terracotta)
	block.set(~ ~11 ~7, minecraft:yellow_terracotta)
	block.set(~ ~5 ~8, minecraft:white_terracotta)
	block.set(~ ~7 ~8, minecraft:white_terracotta)
	block.set(~ ~9 ~8, minecraft:white_terracotta)
	block.set(~ ~11 ~8, minecraft:blue_terracotta)
	block.set(~ ~5 ~9, minecraft:white_terracotta)
	block.set(~ ~7 ~9, minecraft:pink_terracotta)
	block.set(~ ~8 ~9, minecraft:orange_terracotta)
	block.set(~ ~9 ~9, minecraft:lime_terracotta)
	block.set(~ ~5 ~10, minecraft:magenta_terracotta)
	block.set(~ ~6 ~10, minecraft:orange_terracotta)
	block.set(~ ~7 ~10, minecraft:lime_terracotta)
}