package level
def @level load_7103238(){
	author("TheblueMan003")
	block.set(~ ~2 ~3, minecraft:light_blue_terracotta)
	block.set(~ ~3 ~3, minecraft:yellow_terracotta)
	block.set(~ ~2 ~4, minecraft:white_terracotta)
	block.set(~ ~3 ~4, minecraft:white_terracotta)
	block.set(~ ~9 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~4, minecraft:yellow_terracotta)
	block.set(~ ~2 ~5, minecraft:pink_terracotta)
	block.set(~ ~3 ~5, minecraft:lime_terracotta)
	block.set(~ ~8 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~5, minecraft:lime_terracotta)
	block.set(~ ~10 ~5, minecraft:magenta_terracotta)
	block.set(~ ~11 ~5, minecraft:yellow_terracotta)
	block.set(~ ~1 ~6, minecraft:brown_terracotta)
	block.set(~ ~2 ~6, minecraft:cyan_terracotta)
	block.set(~ ~3 ~6, minecraft:orange_terracotta)
	block.set(~ ~4 ~6, minecraft:yellow_terracotta)
	block.set(~ ~7 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~6, minecraft:lime_terracotta)
	block.set(~ ~9 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~6, minecraft:yellow_terracotta)
	block.set(~ ~11 ~6, minecraft:magenta_terracotta)
	block.set(~ ~12 ~6, minecraft:yellow_terracotta)
	block.set(~ ~4 ~7, minecraft:magenta_terracotta)
	block.set(~ ~5 ~7, minecraft:gray_terracotta)
	block.set(~ ~6 ~7, minecraft:orange_terracotta)
	block.set(~ ~7 ~7, minecraft:cyan_terracotta)
	block.set(~ ~8 ~7, minecraft:yellow_terracotta)
	block.set(~ ~9 ~7, minecraft:magenta_terracotta)
	block.set(~ ~10 ~7, minecraft:lime_terracotta)
	block.set(~ ~11 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~12 ~7, minecraft:lime_terracotta)
	block.set(~ ~5 ~8, minecraft:pink_terracotta)
	block.set(~ ~6 ~8, minecraft:yellow_terracotta)
	block.set(~ ~8 ~8, minecraft:magenta_terracotta)
	block.set(~ ~9 ~8, minecraft:yellow_terracotta)
	block.set(~ ~10 ~8, minecraft:light_blue_terracotta)
	block.set(~ ~11 ~8, minecraft:lime_terracotta)
	block.set(~ ~5 ~9, minecraft:white_terracotta)
	block.set(~ ~6 ~9, minecraft:white_terracotta)
	block.set(~ ~9 ~9, minecraft:magenta_terracotta)
	block.set(~ ~10 ~9, minecraft:lime_terracotta)
	block.set(~ ~5 ~10, minecraft:magenta_terracotta)
	block.set(~ ~6 ~10, minecraft:lime_terracotta)
}