package level
def @level load_7632069(){
	author("TheblueMan003")
	block.set(~ ~3 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~4 ~5, minecraft:orange_terracotta)
	block.set(~ ~5 ~5, minecraft:orange_terracotta)
	block.set(~ ~6 ~5, minecraft:yellow_terracotta)
	block.set(~ ~2 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~3 ~6, minecraft:lime_terracotta)
	block.set(~ ~4 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~6, minecraft:red_terracotta)
	block.set(~ ~6 ~6, minecraft:magenta_terracotta)
	block.set(~ ~7 ~6, minecraft:orange_terracotta)
	block.set(~ ~8 ~6, minecraft:yellow_terracotta)
	block.set(~ ~2 ~7, minecraft:white_terracotta)
	block.set(~ ~3 ~7, minecraft:brown_terracotta)
	block.set(~ ~4 ~7, minecraft:lime_terracotta)
	block.set(~ ~5 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~7, minecraft:orange_terracotta)
	block.set(~ ~7 ~7, minecraft:red_terracotta)
	block.set(~ ~8 ~7, minecraft:pink_terracotta)
	block.set(~ ~9 ~7, minecraft:orange_terracotta)
	block.set(~ ~10 ~7, minecraft:red_terracotta)
	block.set(~ ~2 ~8, minecraft:magenta_terracotta)
	block.set(~ ~3 ~8, minecraft:yellow_terracotta)
	block.set(~ ~4 ~8, minecraft:brown_terracotta)
	block.set(~ ~5 ~8, minecraft:lime_terracotta)
	block.set(~ ~6 ~8, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~8, minecraft:orange_terracotta)
	block.set(~ ~8 ~8, minecraft:lime_terracotta)
	block.set(~ ~3 ~9, minecraft:magenta_terracotta)
	block.set(~ ~4 ~9, minecraft:orange_terracotta)
	block.set(~ ~5 ~9, minecraft:orange_terracotta)
	block.set(~ ~6 ~9, minecraft:lime_terracotta)
}