package level
def @level load_8406883(){
	author("TheblueMan003")
	block.set(~ ~8 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~4, minecraft:orange_terracotta)
	block.set(~ ~10 ~4, minecraft:yellow_terracotta)
	block.set(~ ~7 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~5, minecraft:lime_terracotta)
	block.set(~ ~10 ~5, minecraft:white_terracotta)
	block.set(~ ~6 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~6, minecraft:lime_terracotta)
	block.set(~ ~9 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~6, minecraft:lime_terracotta)
	block.set(~ ~6 ~7, minecraft:magenta_terracotta)
	block.set(~ ~7 ~7, minecraft:yellow_terracotta)
	block.set(~ ~9 ~7, minecraft:magenta_terracotta)
	block.set(~ ~10 ~7, minecraft:yellow_terracotta)
	block.set(~ ~7 ~8, minecraft:magenta_terracotta)
	block.set(~ ~8 ~8, minecraft:yellow_terracotta)
	block.set(~ ~10 ~8, minecraft:white_terracotta)
	block.set(~ ~8 ~9, minecraft:magenta_terracotta)
	block.set(~ ~9 ~9, minecraft:orange_terracotta)
	block.set(~ ~10 ~9, minecraft:lime_terracotta)
}