package level
def @level load_8570589(){
	author("TheblueMan003")
	block.set(~ ~4 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~4, minecraft:orange_terracotta)
	block.set(~ ~6 ~4, minecraft:red_terracotta)
	block.set(~ ~7 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~4, minecraft:orange_terracotta)
	block.set(~ ~9 ~4, minecraft:orange_terracotta)
	block.set(~ ~10 ~4, minecraft:yellow_terracotta)
	block.set(~ ~4 ~5, minecraft:magenta_terracotta)
	block.set(~ ~5 ~5, minecraft:red_terracotta)
	block.set(~ ~6 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~7 ~5, minecraft:lime_terracotta)
	block.set(~ ~8 ~5, minecraft:green_terracotta)
	block.set(~ ~9 ~5, minecraft:green_terracotta)
	block.set(~ ~10 ~5, minecraft:blue_terracotta)
	block.set(~ ~4 ~6, minecraft:brown_terracotta)
	block.set(~ ~5 ~6, minecraft:orange_terracotta)
	block.set(~ ~6 ~6, minecraft:lime_terracotta)
	block.set(~ ~7 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~8 ~6, minecraft:lime_terracotta)
	block.set(~ ~9 ~6, minecraft:magenta_terracotta)
	block.set(~ ~10 ~6, minecraft:yellow_terracotta)
	block.set(~ ~4 ~7, minecraft:brown_terracotta)
	block.set(~ ~5 ~7, minecraft:orange_terracotta)
	block.set(~ ~6 ~7, minecraft:yellow_terracotta)
	block.set(~ ~7 ~7, minecraft:magenta_terracotta)
	block.set(~ ~8 ~7, minecraft:yellow_terracotta)
	block.set(~ ~9 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~7, minecraft:lime_terracotta)
	block.set(~ ~4 ~8, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~8, minecraft:red_terracotta)
	block.set(~ ~6 ~8, minecraft:magenta_terracotta)
	block.set(~ ~7 ~8, minecraft:yellow_terracotta)
	block.set(~ ~8 ~8, minecraft:blue_terracotta)
	block.set(~ ~9 ~8, minecraft:blue_terracotta)
	block.set(~ ~10 ~8, minecraft:green_terracotta)
	block.set(~ ~4 ~9, minecraft:magenta_terracotta)
	block.set(~ ~5 ~9, minecraft:orange_terracotta)
	block.set(~ ~6 ~9, minecraft:red_terracotta)
	block.set(~ ~7 ~9, minecraft:magenta_terracotta)
	block.set(~ ~8 ~9, minecraft:orange_terracotta)
	block.set(~ ~9 ~9, minecraft:orange_terracotta)
	block.set(~ ~10 ~9, minecraft:lime_terracotta)
}