package level
def @level load_9054287(){
	author("TheblueMan003")
	block.set(~ ~8 ~3, minecraft:light_blue_terracotta)
	block.set(~ ~9 ~3, minecraft:yellow_terracotta)
	block.set(~ ~8 ~4, minecraft:white_terracotta)
	block.set(~ ~9 ~4, minecraft:white_terracotta)
	block.set(~ ~5 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~5, minecraft:orange_terracotta)
	block.set(~ ~7 ~5, minecraft:orange_terracotta)
	block.set(~ ~8 ~5, minecraft:lime_terracotta)
	block.set(~ ~9 ~5, minecraft:white_terracotta)
	block.set(~ ~5 ~6, minecraft:magenta_terracotta)
	block.set(~ ~6 ~6, minecraft:orange_terracotta)
	block.set(~ ~7 ~6, minecraft:yellow_terracotta)
	block.set(~ ~9 ~6, minecraft:magenta_terracotta)
	block.set(~ ~10 ~6, minecraft:orange_terracotta)
	block.set(~ ~11 ~6, minecraft:yellow_terracotta)
	block.set(~ ~5 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~7, minecraft:orange_terracotta)
	block.set(~ ~7 ~7, minecraft:lime_terracotta)
	block.set(~ ~9 ~7, minecraft:light_blue_terracotta)
	block.set(~ ~10 ~7, minecraft:orange_terracotta)
	block.set(~ ~11 ~7, minecraft:lime_terracotta)
	block.set(~ ~5 ~8, minecraft:magenta_terracotta)
	block.set(~ ~6 ~8, minecraft:orange_terracotta)
	block.set(~ ~7 ~8, minecraft:orange_terracotta)
	block.set(~ ~8 ~8, minecraft:yellow_terracotta)
	block.set(~ ~9 ~8, minecraft:white_terracotta)
	block.set(~ ~8 ~9, minecraft:white_terracotta)
	block.set(~ ~9 ~9, minecraft:white_terracotta)
	block.set(~ ~8 ~10, minecraft:magenta_terracotta)
	block.set(~ ~9 ~10, minecraft:lime_terracotta)
}