package level
def @level load_9883888(){
	author("TheblueMan003")
	block.set(~ ~4 ~3, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~3, minecraft:yellow_terracotta)
	block.set(~ ~3 ~4, minecraft:light_blue_terracotta)
	block.set(~ ~4 ~4, minecraft:lime_terracotta)
	block.set(~ ~5 ~4, minecraft:magenta_terracotta)
	block.set(~ ~6 ~4, minecraft:yellow_terracotta)
	block.set(~ ~2 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~3 ~5, minecraft:lime_terracotta)
	block.set(~ ~5 ~5, minecraft:light_blue_terracotta)
	block.set(~ ~6 ~5, minecraft:lime_terracotta)
	block.set(~ ~2 ~6, minecraft:white_terracotta)
	block.set(~ ~4 ~6, minecraft:light_blue_terracotta)
	block.set(~ ~5 ~6, minecraft:lime_terracotta)
	block.set(~ ~2 ~7, minecraft:magenta_terracotta)
	block.set(~ ~3 ~7, minecraft:yellow_terracotta)
	block.set(~ ~4 ~7, minecraft:magenta_terracotta)
	block.set(~ ~5 ~7, minecraft:yellow_terracotta)
	block.set(~ ~3 ~8, minecraft:magenta_terracotta)
	block.set(~ ~4 ~8, minecraft:yellow_terracotta)
	block.set(~ ~5 ~8, minecraft:magenta_terracotta)
	block.set(~ ~6 ~8, minecraft:yellow_terracotta)
	block.set(~ ~4 ~9, minecraft:magenta_terracotta)
	block.set(~ ~5 ~9, minecraft:yellow_terracotta)
	block.set(~ ~6 ~9, minecraft:magenta_terracotta)
	block.set(~ ~7 ~9, minecraft:yellow_terracotta)
	block.set(~ ~5 ~10, minecraft:magenta_terracotta)
	block.set(~ ~6 ~10, minecraft:yellow_terracotta)
	block.set(~ ~7 ~10, minecraft:magenta_terracotta)
	block.set(~ ~8 ~10, minecraft:yellow_terracotta)
	block.set(~ ~6 ~11, minecraft:magenta_terracotta)
	block.set(~ ~7 ~11, minecraft:yellow_terracotta)
	block.set(~ ~8 ~11, minecraft:magenta_terracotta)
	block.set(~ ~9 ~11, minecraft:yellow_terracotta)
	block.set(~ ~7 ~12, minecraft:magenta_terracotta)
	block.set(~ ~8 ~12, minecraft:orange_terracotta)
	block.set(~ ~9 ~12, minecraft:lime_terracotta)
}